apiVersion: apps/v1
kind: Deployment

metadata:
  name: registration-form-deployment

spec:
  replicas: 4

  selector:
    matchLabels:
      app: registration-form

  template:
    metadata:
      labels:
        app: registration-form

    spec:
      containers:
        - name: registration-form
          image: saibhavani12/registration-form:latest

          ports:
            - containerPort: 5000